import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './questionnaire.css';
import All from '/Users/sophielebron/Desktop/coding-projects/what-to-do-in-denver/src/pages/all/all.js';

function Questionnaire() {
    const [selectedOptions, setSelectedOptions] = useState([]);
    const [allActivities, setAllActivities] = useState([]);
    const [showActivities, setShowActivities] = useState(false);
    const navigate = useNavigate();

    const all = [
        {
            id: 0,
            "title": "Ski at Copper Mountain",
            "image": "https://cdn.5280.com/2022/12/00_Copper-50th_hero-2022-960x720.jpg",
            "description": "Copper mountain has ski runs for all levels, with the West side of the mountain perfect for beginners, and the East side perfect for more advanced skiers.",
            "webUrl": "https://www.coppercolorado.com/?gad=1&gclid=CjwKCAjwvJyjBhApEiwAWz2nLTRE0uQhhwPWLZodgz0BoOK4v_snaemFEBG_UMGRDX9AMDrQrzfRsBoCYlYQAvD_BwE&gclsrc=aw.ds",
            "halfDay": true,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 1,
            "title": "Visit Denver Museum of Nature & Science",
            "image": "https://media2.westword.com/den/imager/u/slideshow/10120352/dmnsdino.jpg",
            "description": "Learn about everything from dinosaurs to astronomy at the Denver Museum of Nature & Science!",
            "webUrl": "https://www.dmns.org/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": false,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 2,
            "title": "Go to a Rockies Game at Coors Field",
            "image": "https://assets.simpleviewinc.com/simpleview/image/upload/crm/denver/Colorado-Rockies_7C649933-EFF0-51B0-9A02E85385D86848_7c6e2c50-dc33-ec19-aec679274174a195.jpg",
            "description": "Watch the Rockies play at the iconic Coors Field. There are lots of bars and restaurants nearby to visit before or after the game!",
            "webUrl": "https://www.mlb.com/rockies/ballpark",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": false,
        },
        {
            id: 3,
            "title": "Ski at Steamboat Ski Resort",
            "image": "https://www.steamboat-springs.com/assets/page_headers/Steamboat_Ski_Resort.jpg",
            "description": "Ski during the day or night at Steamboat Ski Resort!",
            "webUrl": "https://www.steamboat.com/",
            "halfDay": false,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 4,
            "title": "Go to Broncos Game at Mile High",
            "image": "https://www.stadiumsofprofootball.com/wp-content/uploads/2016/07/milehigh21951.jpg",
            "description": "See the Broncos play at Empower Field at Mile High Stadium.",
            "webUrl": "https://www.empowerfieldatmilehigh.com/events-tickets/denver-broncos",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": true,
        },
        {
            id: 5,
            "title": "Go to an Avalanche Game",
            "image": "https://kdvr.com/wp-content/uploads/sites/11/2022/06/GettyImages-1403173601.jpg?w=2560&h=1440&crop=1",
            "description": "See Colorado's NHL team play at Ball Arena.",
            "webUrl": "https://www.nhl.com/avalanche",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": false,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": true,
        },
        {
            id: 6,
            "title": "Ski at Winter Park",
            "image": "https://res.cloudinary.com/miles-extranet-dev/image/upload/v1582130613/Winter_Park/account_photos/45/5b529c7b4d8857a8d81c9a2117ee42aa_2019_WP_CharlesStemen_DSC024631.jpg",
            "description": "Winter Park is a very beginner friendly ski resort located just 75 miles from Denver.",
            "webUrl": "https://www.winterparkresort.com/",
            "halfDay": true,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 7,
            "title": "Ski at Aspen Snowmass Ski Resort",
            "image": "https://www.aspensnowmass.com/-/media/aspen-snowmass/images/hero/hero-image/winter/2021-22/snowmass-hero-08182021.jpg?mw=1506&mh=930&hash=8711362070C02D29B00C0D09593FB504",
            "description": "Ski at one of the four resorts (Aspen, Aspen Highlands, Snowmass, and Buttermilk) that make up the Aspen Snowmass Ski Resort!",
            "webUrl": "https://www.aspensnowmass.com/",
            "halfDay": false,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 8,
            "title": "Go to a Nuggets Game at Ball Arena",
            "image": "https://www.denverpost.com/wp-content/uploads/2023/06/TDP-L-NUGGS-HEAT-GAME-ONE_DSC5093.jpg?w=1024",
            "description": "See Denver's NBA team, the Nuggets, play at Ball Arena.",
            "webUrl": "https://www.ballarena.com/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": false,
            "winter": true,
            "spring": true,
            "summer": false,
            "fall": true,
        },
        {
            id: 9,
            "title": "Visit Rocky Mountain National Park",
            "image": "https://www.jellystoneofestes.com/wp-content/uploads/2016/12/rockymountain.jpg",
            "description": "Hike, drive, camp, and see wildlife at Rocky Mountain National Park.",
            "webUrl": "https://www.nps.gov/romo/index.htm",
            "halfDay": false,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 10,
            "title": "Devil's Head Lookout Hike",
            "image": "https://dayhikesneardenver.b-cdn.net/wp-content/uploads/2013/03/devils_head_northtolongs.jpg",
            "description": "Hike to a U.S. Forest Service fire lookout tower for a beautiful view of Pike National Forest.",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/devil-s-head-lookout-trail--2",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 11,
            "title": "Go To Washington Park",
            "image": "https://img1.10bestmedia.com/Images/Photos/334671/p-IMG-4408_55_660x440.jpg",
            "description": "Have a picnic, play volleyball, or go for a walk in Washington Park.",
            "webUrl": "https://www.denver.org/listing/washington-park/6828/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 12,
            "title": "Hike the Manitou Incline",
            "image": "https://bloximages.newyork1.vip.townnews.com/gazette.com/content/tncms/assets/v3/editorial/4/32/432e47c8-df3b-52bb-9f2a-5add02b8ddd3/5f501230a7b39.image.jpg?crop=1247%2C1247%2C207%2C0&resize=1247%2C1247&order=crop%2Cresize",
            "description": "Hike this challenging route which consists of over 2,700 steps.",
            "webUrl": "https://manitousprings.org/where-to-play/manitou-incline/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": false,
            "summer": true,
            "fall": true,
        },
        {
            id: 13,
            "title": "Peak to Peak Scenic Byway",
            "image": "https://www.gocolorado.com/wp-content/uploads/2010/11/peaktopeak.jpg",
            "description": "A 55 mile drive that has views of the Rocky Mountains.",
            "webUrl": "https://www.codot.gov/travel/colorado-byways/north-central/peak-to-peak",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": false,
            "summer": true,
            "fall": true,
        },
        {
            id: 14,
            "title": "Visit Union Station",
            "image": "https://media.cntraveler.com/photos/5bdb4ac22e350417aea9d74b/16:9/w_2560,c_limit/Denver%20Union%20Station_DUSExtJune20_2.jpg",
            "description": "Explore restaurants and shops in Denver's downtown train station.",
            "webUrl": "https://www.denverunionstation.com/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": false,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 15,
            "title": "Go to a Concert at Red Rocks",
            "image": "https://images.squarespace-cdn.com/content/v1/52991237e4b06b094787fe1d/1558644190914-6TOUJP92QK2JY0NNH9JW/printshop11.jpg?format=1500w",
            "description": "Enjoy live music at one of the country's most beautiful natural outdoor venues.",
            "webUrl": "https://www.theredrocksamphitheater.com/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 16,
            "title": "Tubing at Clear Creek",
            "image": "https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,h_1200,q_75,w_1200/v1/clients/goldenco/TubingClearCreek_1_5c3c2930-cc7d-433d-88c4-e6657b85a169.jpg",
            "description": "Clear Creek is a popular spot for tubing during the summer.",
            "webUrl": "https://www.cityofgolden.net/play/recreation-attractions/clear-creek-white-water-park/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": false,
            "summer": true,
            "fall": false,
        },
        {
            id: 17,
            "title": "Visit Great Sand Dunes National Park",
            "image": "https://www.nps.gov/grsa/planyourvisit/images/grsa-fresh-snow-mts-gold-cottonwoods-2018-jpg.jpg?maxwidth=1300&maxheight=1300&autorotate=false",
            "description": "Experience the tallest sand dunes in North America!",
            "webUrl": "https://www.nps.gov/grsa/index.htm",
            "halfDay": false,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 18,
            "title": "Hike to Maroon Bells",
            "image": "https://upload.wikimedia.org/wikipedia/commons/5/53/Maroon_Bells_%2811553%29a.jpg",
            "description": "Hike to see one of the most recognizable mountains in the United States.",
            "webUrl": "https://www.colorado.com/articles/explore-maroon-bells-what-you-need-know",
            "halfDay": false,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": false,
            "summer": true,
            "fall": true,
        },
        {
            id: 19,
            "title": "Visit Mesa Verde National Park",
            "image": "https://eoimages.gsfc.nasa.gov/images/imagerecords/88000/88632/99C97231-1DD8-B71B-0B80F0D734C77303_lrg.jpg",
            "description": "See the cliff dwellings that Ancestral Puebloans lived in hundreds of years ago.",
            "webUrl": "https://www.nps.gov/meve/index.htm",
            "halfDay": false,
            "fullDay": false,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 20,
            "title": "Visit Black Canyon of the Gunnison National Park",
            "image": "https://www.magnificentworld.com/wp-content/uploads/2021/02/Black-Canyon-of-the-Gunnison.jpg",
            "description": "Head to western Colorado to see one of the most narrow canyons in North America.",
            "webUrl": "https://www.nps.gov/blca/index.htm",
            "halfDay": false,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 21,
            "title": "Go for a Bike Ride on Cherry Creek Trail",
            "image": "https://res.cloudinary.com/simpleview/image/upload/v1476756488/clients/denver/cherry-creek-path-bikes_57313449-f0ae-5102-065bde7317fe103b.jpg",
            "description": "Ride your bike down part or all of this 40 mile paved trail.",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/cherry-creek-trail",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
        id: 22,
            "title": "Go to Cherry Creek Dog Off Leash Area",
            "image": "https://1.bp.blogspot.com/-9xJVEqKZmjw/VV_MA8dOEII/AAAAAAAAOwI/1Un4XEC4jfQ/s1600/DSC05583%2B%25282%2529.JPG",
            "description": "Enjoy the day running and splashing around with your pooch!",
            "webUrl": "https://cpw.state.co.us/placestogo/parks/CherryCreek/Pages/DogOff-LeashArea.aspx",
            "halfDay": true,
            "fullDay": true,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 23,
            "title": "Horseback Riding at 12 Mile Stables",
            "image": "https://i.ytimg.com/vi/rnDGyGGQXww/sddefault.jpg",
            "description": "Spend an afternoon horseback riding through Cherry Creek State Park.",
            "webUrl": "https://www.horserentalsdenver.com/horse-rentals",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 24,
            "title": "Ski at Vail",
            "image": "https://scene7.vailresorts.com/is/image/vailresorts/20230112_VL_DUNN_-02_flipped:Media-Gallery?resMode=sharp2&w=720&h=495&wid=400&fit=constrain,1&dpr=on,2",
            "description": "Ski at one of Colorado's most popular ski resorts.",
            "webUrl": "https://www.vail.com/",
            "halfDay": true,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 25,
            "title": "Go to Ready Paint Fire",
            "image": "https://i0.wp.com/rpfbreck.com/wp-content/uploads/2023/08/3529.jpg?w=1000&ssl=1",
            "description": "Paint, make candles, and more at this fun art studio in Breckenridge.",
            "webUrl": "https://rpfbreck.com/",
            "halfDay": true,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": true,
            "outdoors": false,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 26,
            "title": "Go to Glenwood Hot Springs Resort",
            "image": "https://hanginglake.com/wp-content/uploads/2023/11/ec87249fa4e2e17ac5ffac374426639e8a859583-2-2048x1399.jpg",
            "description": "Relax in the hot springs and maybe stay the night at this beautiful hot springs resort.",
            "webUrl": "https://www.hotspringspool.com/",
            "halfDay": false,
            "fullDay": true,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": true,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 27,
            "title": "Dog Sledding at Mountain Musher",
            "image": "https://www.mountainmusher.com/images/gallery/IMG_9835.JPG",
            "description": "Ride a sled pulled by a team of huskies through the mountains in Eagle County.",
            "webUrl": "https://www.mountainmusher.com/index.php",
            "halfDay": false,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 28,
            "title": "Ski at Arapahoe Basin",
            "image": "https://www.coloradoski.com/wp-content/uploads/2022/09/arapahoe-basin-skier.jpeg",
            "description": "Spend the day skiing at this ski area perfect for intermediate and advanced skiers.",
            "webUrl": "https://www.arapahoebasin.com/",
            "halfDay": true,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 29,
            "title": "Summit Mount Bierstadt",
            "image": "https://bearfoottheory.com/wp-content/uploads/2021/06/Mount-Bierstadt-Colorado-14er.jpeg",
            "description": "A great beginner (but still challenging!) hike for those who are looking to tackle their first 14er.",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/mount-bierstadt-trail",
            "halfDay": false,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": false,
            "summer": true,
            "fall": true,
        },
        {
            id: 30,
            "title": "Terror in the Corn",
            "image": "https://terrorinthecorn.com/wp-content/uploads/2019/03/terror-in-the-corn-mobile-1.jpg",
            "description": "Visit this spooky mile long haunted corn maze during the Halloween season, or visit Anderson Farms during the day for their Fall Festival!",
            "webUrl": "https://terrorinthecorn.com/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": false,
            "summer": false,
            "fall": true,
        },
        {
            id: 31,
            "title": "Get Brunch at Olive and Finch",
            "image": "https://media.cntraveler.com/photos/5bdb147ecfd2bb17f97a78da/16:9/w_2560,c_limit/Olive-and-Finch-(17th-Ave.)_DSC_0013.jpg",
            "description": "Grab breakfast, lunch, or a snack at this charming restaurant and bakery.",
            "webUrl": "https://www.oliveandfinch.com/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 32,
            "title": "Hike to Horsetooth Rock",
            "image": "https://www.larimer.gov/sites/default/files/06_horsetooth_mountain_01_by_jeanie_sumrall-ajero.jpg",
            "description": "Head up to Fort Collins to hike this 6 mile loop that takes you to Horsetooth Rock!",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/horsetooth-falls-and-horsetooth-rock-trail",
            "halfDay": true,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 33,
            "title": "Ski at Telluride",
            "image": "https://cloudfront-ap-southeast-2.images.arcpublishing.com/nzme/JLSIWGVAQR7XQJD6UA7UODGL7E.jpg",
            "description": "Take a short trip to Telluride to ski and explore this beautiful mountain town.",
            "webUrl": "https://tellurideskiresort.com/",
            "halfDay": false,
            "fullDay": false,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 34,
            "title": "Get Lunch or Dinner at North Italia",
            "image": "https://tcf-north-italia.s3-us-west-1.amazonaws.com/wp-content/uploads/2017/10/07175549/NEW-Denver-Cherry-Creek_PDR.jpg",
            "description": "Head over to Cherry Creek for some yummy italian food!",
            "webUrl": "https://www.northitalia.com/locations/denver-co-cherry-creek-shopping-center/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 35,
            "title": "Go to City Park",
            "image": "https://assets.simpleviewinc.com/simpleview/image/upload/crm/denver/Skyline-from-City-Park-Credit-VISIT-DENVER_ff0ebf30-9974-d6f4-c30321bf4a19c06e.jpg",
            "description": "Have a picnic, go for a run, walk your dog, play tennis, and more at Denver's biggest park.",
            "webUrl": "https://www.denver.org/listing/city-park/6822/",
            "halfDay": true,
            "fullDay": true,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 35,
            "title": "Go to Denver Botanic Gardens",
            "image": "https://img1.10bestmedia.com/Images/Photos/389658/Botanic-Gardens-Pond-Pavilion-LR_55_660x440.jpg",
            "description": "Spend a morning or afternoon exploring 23 acres of beautiful gardens!",
            "webUrl": "https://www.botanicgardens.org/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 36,
            "title": "Ski at Eldora",
            "image": "https://www.eldora.com/_gatsby/image/2d393c95cc8f3ca329af2c72ecc9b498/bdc403eda6842382158698ab1a77c7a7/New223_NewHome_10.23.webp?u=https%3A%2F%2Fcms.eldora.com%2Fsites%2Fdefault%2Ffiles%2F2023-10%2FNew223_NewHome_10.23.jpg&a=w%3D960%26h%3D456%26fm%3Dwebp%26q%3D90&cd=9369667a1a76c1ac4eb7c88ad91d22c3",
            "description": "Not far outside of Boulder, Eldora is a great mountain for a quick day trip!",
            "webUrl": "https://www.eldora.com/",
            "halfDay": true,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": false,
            "summer": false,
            "fall": false,
        },
        {
            id: 37,
            "title": "Hike Arthur's Rock Trail",
            "image": "https://cdn.backpacker.com/wp-content/uploads/2013/09/arthurs-rock.jpg?width=730",
            "description": "Head to Lory State Park for this beautiful out and back hike.",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/arthurs-rock",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 38,
            "title": "Go To Big B's Soup & Grilled Cheese",
            "image": "https://cheesus.biz/wp-content/uploads/2020/12/BigBs_IdahoSprings-36.jpg",
            "description": "The tomato stuffed grilled cheese is a must try!",
            "webUrl": "https://cheesus.biz/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": true,
            "outdoors": false,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 39,
            "title": "See a Movie at Holiday Twin Drive-In",
            "image": "https://www.colorado.com/sites/default/files/listing_images/profile/6468/sunset2017.jpg",
            "description": "Pack some snacks and blankets and drive up to Fort Collins to catch a movie at a drive-in theater!",
            "webUrl": "https://holidaytwin.com/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 40,
            "title": "Hike To Saint Mary's Glacier",
            "image": "https://www.foxintheforest.net/wp-content/uploads/2022/01/iStock-1294952554.jpg",
            "description": "This short hike near Idaho Springs offers beautiful views of the Rocky Mountains and Saint Mary's Glacier and Lake.",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/st-mary-s-glacier",
            "halfDay": true,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 41,
            "title": "Go Rock Climbing at Movement",
            "image": "https://movementgyms.com/app/uploads/sites/33/2023/04/Web-Large-Cruxing-in-Color_Baker_MVMT_2022_MHecker-153.jpg",
            "description": "Boulder or top rope at one of Movement's three locations in Denver.",
            "webUrl": "https://movementgyms.com/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": false,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 42,
            "title": "Go To A Colorado Ballet Performance",
            "image": "https://coloradoballet.org/files/_cache/de7d3318ac54628a05c899878a1ddb09.jpg",
            "description": "Spend an evening watching a performance by Colorado Ballet. Check their website for upcoming performances.",
            "webUrl": "https://coloradoballet.org/?_ga=2.45474407.2108115840.1709745453-1041311232.1709745453",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": false,
            "winter": true,
            "spring": true,
            "summer": false,
            "fall": true,
        },
        {
            id: 43,
            "title": "Hike Clayton Lake Trail",
            "image": "https://images.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMjM3MTE0MzgvZTU2Y2FjYjc3MGUzMDA1ZTUzZmVmYzI3YjE5YTIzMGEuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjo1MDAsImhlaWdodCI6NTAwLCJmaXQiOiJpbnNpZGUifSwicm90YXRlIjpudWxsLCJqcGVnIjp7InRyZWxsaXNRdWFudGlzYXRpb24iOnRydWUsIm92ZXJzaG9vdERlcmluZ2luZyI6dHJ1ZSwib3B0aW1pc2VTY2FucyI6dHJ1ZSwicXVhbnRpc2F0aW9uVGFibGUiOjN9fX0=",
            "description": "Bring your dog for this out-and-back hike to Clayton Lake in James Peak Wilderness.",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/clayton-lake-james-peak-wilderness",
            "halfDay": false,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 44,
            "title": "Camp at Cold Springs Campground",
            "image": "https://savageventures.b-cdn.net/wp-content/uploads/2016/06/stelprdb5183583.jpg",
            "description": "Go camping at Cold Springs Campground, located outside of Idaho Springs. There are hiking trails and fishing spots nearby.",
            "webUrl": "https://www.fs.usda.gov/recarea/arp/recarea/?recid=28410",
            "halfDay": false,
            "fullDay": false,
            "overnight": true,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 45,
            "title": "Copper Rocky Mountain Coaster",
            "image": "https://www.denverpost.com/wp-content/uploads/2020/10/Copper_Mountain_set_new_visitation_records_for_summer_attractions_despite_pandemic_giving_hope_for_strong_ski_season_1.jpg?w=978",
            "description": "Whizz down the mountain on one of the longest alpine coasters in North America!",
            "webUrl": "https://www.coppercolorado.com/things-to-do/activities-amenities/coaster",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 46,
            "title": "Go for a Run on Cherry Creek Trail",
            "image": "https://greatruns.com/wp-content/uploads/2016/08/denver-cherry-creek.jpeg",
            "description": "Go for a run on this 40 mile paved trail that runs along the Cherry Creek and South Platte River.",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/cherry-creek-trail",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 47,
            "title": "Go to Dillon Reservoir",
            "image": "https://adventurepaddletours.com/wp-content/uploads/2023/01/Dillon-Reservoir-2.jpg",
            "description": "Visit Dillon Reservoir to kayak, paddleboard, hike, go for a picnic, etc!",
            "webUrl": "https://www.denverwater.org/recreation/dillon-resevoir",
            "halfDay": false,
            "fullDay": true,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": false,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 48,
            "title": "Visit Crested Butte",
            "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/51/ea/4e/kebler-pass.jpg?w=500&h=400&s=1",
            "description": "Take an overnight or weekend trip to Crested Butte.",
            "webUrl": "https://www.skicb.com/",
            "halfDay": false,
            "fullDay": false,
            "overnight": true,
            "inCity": false,
            "oneHr": false,
            "fewHours": true,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 49,
            "title": "Hike Panorama Point",
            "image": "https://www.alltrails.com/_next/image?url=https%3A%2F%2Fimages.alltrails.com%2FeyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMjg4OTQxMjcvZjkzNDA1MDNlOTcwZWQ3ZmI2MzQ2MWZkNjc4OGVmYmQuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJ3ZWJwIiwicmVzaXplIjp7IndpZHRoIjoxMDIyLCJoZWlnaHQiOjMxMiwiZml0IjoiY292ZXIifSwicm90YXRlIjpudWxsLCJqcGVnIjp7InRyZWxsaXNRdWFudGlzYXRpb24iOnRydWUsIm92ZXJzaG9vdERlcmluZ2luZyI6dHJ1ZSwib3B0aW1pc2VTY2FucyI6dHJ1ZSwicXVhbnRpc2F0aW9uVGFibGUiOjN9fX0%3D&w=3840&q=90",
            "description": "A great 2 hour hike just outside of Denver!",
            "webUrl": "https://www.alltrails.com/trail/us/colorado/panorama-point-to-bear-creek-trail-loop",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": false,
            "oneHr": true,
            "fewHours": false,
            "indoors": false,
            "outdoors": true,
            "winter": true,
            "spring": true,
            "summer": true,
            "fall": true,
        },
        {
            id: 50,
            "title": "Get Ice Cream at Bonnie Brae",
            "image": "https://live.staticflickr.com/6179/6245164996_b480b184b1_b.jpg",
            "description": "Make a nighttime stop to Bonnie Brae for ice cream or a milkshake!",
            "webUrl": "https://bonniebraeicecream.com/",
            "halfDay": true,
            "fullDay": false,
            "overnight": false,
            "inCity": true,
            "oneHr": false,
            "fewHours": false,
            "indoors": true,
            "outdoors": true,
            "winter": false,
            "spring": false,
            "summer": true,
            "fall": false,
        },
    ];

    const questions = [
        {
            id: 0,
            question: "How long would you like the activity to take?",
            options: [
                { id: 1, label: "Half day" },
                { id: 2, label: "Full day" },
                { id: 3, label: "Overnight" },
            ],
        },
        {
            id: 1,
            question: "How far from Denver would you like to travel?",
            options: [
                { id: 4, label: "Within the city" },
                { id: 5, label: "1 hour" },
                { id: 6, label: "Few hours" },
            ],
        },
        {
            id: 2,
            question: "Would you like to do an indoor or outdoor activity?",
            options: [
                { id: 7, label: "Indoors" },
                { id: 8, label: "Outdoors" },
            ],
        },
        {
            id: 3,
            question: "In what season will you be doing the activity?",
            options: [
                { id: 9, label: "Winter" },
                { id: 10, label: "Spring" },
                { id: 11, label: "Summer" },
                { id: 12, label: "Fall" },
            ],
        },
        // {
        //     id: 4,
        //     question: "Would you like the activity to be dog friendly?",
        //     options: [
        //         { id: 13, label: "Yes" },
        //         { id: 14, label: "No" },
        //     ],
        // },
    ]

    const handleCheckboxChange = (optionId) => {
        setSelectedOptions((prevSelectedOptions) => {
            if (prevSelectedOptions.includes(optionId)) {
                return prevSelectedOptions.filter((id) => id !==optionId);
            } else {
                return [...prevSelectedOptions, optionId];
            }
        });
    };

    const pushToAllActivities = () => {
        const filteredActivities = all.filter(activity => {
            return (
                (
                (selectedOptions.includes(1) && activity.halfDay) ||
                (selectedOptions.includes(2) && activity.fullDay) ||
                (selectedOptions.includes(3) && activity.overnight)
                )
                &&

                (
                (selectedOptions.includes(4) && activity.inCity) ||
                (selectedOptions.includes(5) && activity.oneHr) ||
                (selectedOptions.includes(6) && activity.fewHours)
                )
                &&

                (
                (selectedOptions.includes(7) && activity.indoors) ||
                (selectedOptions.includes(8) && activity.outdoors)
                )
                &&

                (
                (selectedOptions.includes(9) && activity.winter) ||
                (selectedOptions.includes(10) && activity.spring) ||
                (selectedOptions.includes(11) && activity.summer) ||
                (selectedOptions.includes(12) && activity.fall)
                )
            );
    });

    allActivities.push(...filteredActivities);

    setAllActivities(filteredActivities);

    console.log(allActivities);
    console.log(filteredActivities);
    }

    const navigateToAll = () => {
        pushToAllActivities();
        setShowActivities(true);
        navigate('/all', { state: { selectedOptions, allActivities } });
    }

    const navigateToRandom = () => {
        pushToAllActivities();
        setShowActivities(true);
        navigate('/random', { state: { selectedOptions, allActivities } });
    }

    return (
        <div className="questionnaire">
        <div className="questionnaireContainer">
            <div className="qTitle">Questionnaire</div>
            <div className="questions">
                {questions.map((questions) => (
                    <div className="question" key={questions.id}>
                        <div className="questionOnly">{questions.question}</div>
                        {questions.options.map((option) => (
                        <label key={option.id} className="options">
                            <input 
                                type="checkbox"
                                className="selectbox"
                                checked={selectedOptions.includes(option.id)}
                                onChange={() => handleCheckboxChange(option.id)}
                            />
                            {option.label}
                        </label>
                        ))}
                    </div>
                ))}
            </div>
            <div className="buttons">
                    <button onClick={navigateToAll} className="allBtn">All Activities</button>
                    <button onClick={navigateToRandom} className="randomBtn">Random Activity</button>
            </div>
        </div>
        {showActivities && <All allActivities={ allActivities } />}
        {showActivities && <All selectedOptions={ selectedOptions } />}
        </div>
    )

}

export default Questionnaire;